package input.validation;

public enum Commands {
    RUN, MOVE, GO, WALK,
    QUIT, EXIT,
    SAVE, LOAD,
    INVENTORY,
    LOOK,
    EXAMINE, OBSERVE,
    TAKE, PICK, PICKUP, GRAB, GET,
    ATTACK, BATTLE,
    DROP,
    GIVE,
    USE,
    READ,
    OPEN, CLOSE,
    SMELL,
    PULL,
    PUSH,
    CONSUME, EAT, DRINK,
    ENTER,
    TALK,
    BREAK,
    CUT,
    LISTEN,
    UNLOCK,
    JUMP,
    HELP,
    BACK, BACKTRACK
}